#!/bin/sh

rm -rf Pack.hh
echo "/*" >> Pack.hh
echo " * --- Packed Resources ---" >> Pack.hh
echo " */" >> Pack.hh
echo "#pragma once" >> Pack.hh

xxd -i Resources/Hud/pointer.png >> Pack.hh
xxd -i Resources/Hud/play.png >> Pack.hh
xxd -i Resources/Hud/pause.png >> Pack.hh
xxd -i Resources/Hud/expand.png >> Pack.hh
xxd -i Resources/Hud/graph.png >> Pack.hh
xxd -i Resources/Hud/text.png >> Pack.hh
xxd -i Resources/Hud/label.png >> Pack.hh
xxd -i Resources/Hud/node.png >> Pack.hh
xxd -i Resources/Hud/loupe.png >> Pack.hh
xxd -i Resources/Hud/flag.png >> Pack.hh
xxd -i Resources/Hud/marker.png >> Pack.hh
xxd -i Resources/Hud/bug.png >> Pack.hh
xxd -i Resources/Hud/spheres.png >> Pack.hh
xxd -i Resources/Hud/eye.png >> Pack.hh
xxd -i Resources/Hud/white-disk.png >> Pack.hh
xxd -i Resources/background.png >> Pack.hh

xxd -i Resources/cube.vert >> Pack.hh
xxd -i Resources/cube.frag >> Pack.hh

xxd -i Resources/quad.vert >> Pack.hh
xxd -i Resources/quad.frag >> Pack.hh

xxd -i Resources/sphere.vert >> Pack.hh
xxd -i Resources/sphere.frag >> Pack.hh

xxd -i Resources/globe.vert >> Pack.hh
xxd -i Resources/globe.frag >> Pack.hh

xxd -i Resources/graph.vert >> Pack.hh
xxd -i Resources/graph.frag >> Pack.hh

xxd -i Resources/curve.vert >> Pack.hh
xxd -i Resources/curve.frag >> Pack.hh

xxd -i Resources/world.vert >> Pack.hh
xxd -i Resources/world.frag >> Pack.hh

xxd -i Resources/disk-white.png >> Pack.hh
xxd -i Resources/square-white.png >> Pack.hh

xxd -i Resources/sphere.png >> Pack.hh
xxd -i Resources/circle.png >> Pack.hh
xxd -i Resources/target.png >> Pack.hh

# SpaceView

xxd -i Resources/SpaceView/node-activity.png >> Pack.hh

xxd -i Resources/SpaceView/EdgeStyles/circles.png >> Pack.hh
xxd -i Resources/SpaceView/EdgeStyles/cross.png >> Pack.hh
xxd -i Resources/SpaceView/EdgeStyles/dashed.png >> Pack.hh
xxd -i Resources/SpaceView/EdgeStyles/dots.png >> Pack.hh
xxd -i Resources/SpaceView/EdgeStyles/zigzag.png >> Pack.hh
xxd -i Resources/SpaceView/EdgeStyles/solid.png >> Pack.hh
xxd -i Resources/SpaceView/EdgeStyles/squares.png >> Pack.hh
xxd -i Resources/SpaceView/EdgeStyles/triangles.png >> Pack.hh

# WorldView

xxd -i Resources/WorldView/geoline.vert >> Pack.hh
xxd -i Resources/WorldView/geoline.frag >> Pack.hh

# ParticleView

xxd -i Resources/ParticleView/node.vert >> Pack.hh
xxd -i Resources/ParticleView/node.frag >> Pack.hh
xxd -i Resources/ParticleView/physics.cl >> Pack.hh

xxd -i Resources/Earth/black-and-blue.jpg >> Pack.hh
xxd -i Resources/Earth/world-2048x1024.jpg >> Pack.hh
xxd -i Resources/Earth/miller-2048x1502.jpg >> Pack.hh
xxd -i Resources/Earth/miller-2048x1502-bw.jpg >> Pack.hh
xxd -i Resources/Earth/globe.png >> Pack.hh
xxd -i Resources/Earth/world-map-icon.png >> Pack.hh

xxd -i Resources/Spheres/starfield.png >> Pack.hh
xxd -i Resources/Spheres/perlin.jpg >> Pack.hh

xxd -i Resources/Particle/ball.png >> Pack.hh
xxd -i Resources/Particle/metaball.png >> Pack.hh

xxd -i Resources/Countries/ad.png >> Pack.hh
xxd -i Resources/Countries/ae.png >> Pack.hh
xxd -i Resources/Countries/af.png >> Pack.hh
xxd -i Resources/Countries/ag.png >> Pack.hh
xxd -i Resources/Countries/ai.png >> Pack.hh
xxd -i Resources/Countries/al.png >> Pack.hh
xxd -i Resources/Countries/am.png >> Pack.hh
xxd -i Resources/Countries/an.png >> Pack.hh
xxd -i Resources/Countries/ao.png >> Pack.hh
xxd -i Resources/Countries/ar.png >> Pack.hh
xxd -i Resources/Countries/as.png >> Pack.hh
xxd -i Resources/Countries/at.png >> Pack.hh
xxd -i Resources/Countries/au.png >> Pack.hh
xxd -i Resources/Countries/aw.png >> Pack.hh
xxd -i Resources/Countries/ax.png >> Pack.hh
xxd -i Resources/Countries/ba.png >> Pack.hh
xxd -i Resources/Countries/bb.png >> Pack.hh
xxd -i Resources/Countries/bd.png >> Pack.hh
xxd -i Resources/Countries/be.png >> Pack.hh
xxd -i Resources/Countries/bf.png >> Pack.hh
xxd -i Resources/Countries/bg.png >> Pack.hh
xxd -i Resources/Countries/bh.png >> Pack.hh
xxd -i Resources/Countries/bi.png >> Pack.hh
xxd -i Resources/Countries/bj.png >> Pack.hh
xxd -i Resources/Countries/bm.png >> Pack.hh
xxd -i Resources/Countries/bn.png >> Pack.hh
xxd -i Resources/Countries/bo.png >> Pack.hh
xxd -i Resources/Countries/br.png >> Pack.hh
xxd -i Resources/Countries/bs.png >> Pack.hh
xxd -i Resources/Countries/bt.png >> Pack.hh
xxd -i Resources/Countries/bw.png >> Pack.hh
xxd -i Resources/Countries/by.png >> Pack.hh
xxd -i Resources/Countries/bz.png >> Pack.hh
xxd -i Resources/Countries/ca.png >> Pack.hh
xxd -i Resources/Countries/cd.png >> Pack.hh
xxd -i Resources/Countries/cf.png >> Pack.hh
xxd -i Resources/Countries/cg.png >> Pack.hh
xxd -i Resources/Countries/ch.png >> Pack.hh
xxd -i Resources/Countries/ci.png >> Pack.hh
xxd -i Resources/Countries/ck.png >> Pack.hh
xxd -i Resources/Countries/cl.png >> Pack.hh
xxd -i Resources/Countries/cm.png >> Pack.hh
xxd -i Resources/Countries/cn.png >> Pack.hh
xxd -i Resources/Countries/co.png >> Pack.hh
xxd -i Resources/Countries/cr.png >> Pack.hh
xxd -i Resources/Countries/cu.png >> Pack.hh
xxd -i Resources/Countries/cv.png >> Pack.hh
xxd -i Resources/Countries/cx.png >> Pack.hh
xxd -i Resources/Countries/cy.png >> Pack.hh
xxd -i Resources/Countries/cz.png >> Pack.hh
xxd -i Resources/Countries/de.png >> Pack.hh
xxd -i Resources/Countries/dj.png >> Pack.hh
xxd -i Resources/Countries/dk.png >> Pack.hh
xxd -i Resources/Countries/dm.png >> Pack.hh
xxd -i Resources/Countries/do.png >> Pack.hh
xxd -i Resources/Countries/dz.png >> Pack.hh
xxd -i Resources/Countries/ec.png >> Pack.hh
xxd -i Resources/Countries/ee.png >> Pack.hh
xxd -i Resources/Countries/eg.png >> Pack.hh
xxd -i Resources/Countries/er.png >> Pack.hh
xxd -i Resources/Countries/es.png >> Pack.hh
xxd -i Resources/Countries/et.png >> Pack.hh
xxd -i Resources/Countries/eu.png >> Pack.hh
xxd -i Resources/Countries/fi.png >> Pack.hh
xxd -i Resources/Countries/fj.png >> Pack.hh
xxd -i Resources/Countries/fk.png >> Pack.hh
xxd -i Resources/Countries/fm.png >> Pack.hh
xxd -i Resources/Countries/fo.png >> Pack.hh
xxd -i Resources/Countries/fr.png >> Pack.hh
xxd -i Resources/Countries/ga.png >> Pack.hh
xxd -i Resources/Countries/gd.png >> Pack.hh
xxd -i Resources/Countries/ge.png >> Pack.hh
xxd -i Resources/Countries/gg.png >> Pack.hh
xxd -i Resources/Countries/gh.png >> Pack.hh
xxd -i Resources/Countries/gi.png >> Pack.hh
xxd -i Resources/Countries/gl.png >> Pack.hh
xxd -i Resources/Countries/gm.png >> Pack.hh
xxd -i Resources/Countries/gn.png >> Pack.hh
xxd -i Resources/Countries/gq.png >> Pack.hh
xxd -i Resources/Countries/gr-cy.png >> Pack.hh
xxd -i Resources/Countries/gr.png >> Pack.hh
xxd -i Resources/Countries/gs.png >> Pack.hh
xxd -i Resources/Countries/gt.png >> Pack.hh
xxd -i Resources/Countries/gu.png >> Pack.hh
xxd -i Resources/Countries/gw.png >> Pack.hh
xxd -i Resources/Countries/gy.png >> Pack.hh
xxd -i Resources/Countries/hk.png >> Pack.hh
xxd -i Resources/Countries/hn.png >> Pack.hh
xxd -i Resources/Countries/hr.png >> Pack.hh
xxd -i Resources/Countries/ht.png >> Pack.hh
xxd -i Resources/Countries/hu.png >> Pack.hh
xxd -i Resources/Countries/id.png >> Pack.hh
xxd -i Resources/Countries/ie.png >> Pack.hh
xxd -i Resources/Countries/il.png >> Pack.hh
xxd -i Resources/Countries/im.png >> Pack.hh
xxd -i Resources/Countries/in.png >> Pack.hh
xxd -i Resources/Countries/io.png >> Pack.hh
xxd -i Resources/Countries/iq.png >> Pack.hh
xxd -i Resources/Countries/ir.png >> Pack.hh
xxd -i Resources/Countries/is.png >> Pack.hh
xxd -i Resources/Countries/it.png >> Pack.hh
xxd -i Resources/Countries/je.png >> Pack.hh
xxd -i Resources/Countries/jm.png >> Pack.hh
xxd -i Resources/Countries/jo.png >> Pack.hh
xxd -i Resources/Countries/jp.png >> Pack.hh
xxd -i Resources/Countries/ke.png >> Pack.hh
xxd -i Resources/Countries/kg.png >> Pack.hh
xxd -i Resources/Countries/kh.png >> Pack.hh
xxd -i Resources/Countries/ki.png >> Pack.hh
xxd -i Resources/Countries/km.png >> Pack.hh
xxd -i Resources/Countries/kn.png >> Pack.hh
xxd -i Resources/Countries/kp.png >> Pack.hh
xxd -i Resources/Countries/kr.png >> Pack.hh
xxd -i Resources/Countries/kw.png >> Pack.hh
xxd -i Resources/Countries/ky.png >> Pack.hh
xxd -i Resources/Countries/kz.png >> Pack.hh
xxd -i Resources/Countries/la.png >> Pack.hh
xxd -i Resources/Countries/lb.png >> Pack.hh
xxd -i Resources/Countries/lc.png >> Pack.hh
xxd -i Resources/Countries/li.png >> Pack.hh
xxd -i Resources/Countries/lk.png >> Pack.hh
xxd -i Resources/Countries/lr.png >> Pack.hh
xxd -i Resources/Countries/ls.png >> Pack.hh
xxd -i Resources/Countries/lt.png >> Pack.hh
xxd -i Resources/Countries/lu.png >> Pack.hh
xxd -i Resources/Countries/lv.png >> Pack.hh
xxd -i Resources/Countries/ly.png >> Pack.hh
xxd -i Resources/Countries/ma.png >> Pack.hh
xxd -i Resources/Countries/mc.png >> Pack.hh
xxd -i Resources/Countries/md.png >> Pack.hh
xxd -i Resources/Countries/me.png >> Pack.hh
xxd -i Resources/Countries/mg.png >> Pack.hh
xxd -i Resources/Countries/mh.png >> Pack.hh
xxd -i Resources/Countries/ml.png >> Pack.hh
xxd -i Resources/Countries/mn.png >> Pack.hh
xxd -i Resources/Countries/mo.png >> Pack.hh
xxd -i Resources/Countries/mp.png >> Pack.hh
xxd -i Resources/Countries/mq.png >> Pack.hh
xxd -i Resources/Countries/mr.png >> Pack.hh
xxd -i Resources/Countries/ms.png >> Pack.hh
xxd -i Resources/Countries/mt.png >> Pack.hh
xxd -i Resources/Countries/mu.png >> Pack.hh
xxd -i Resources/Countries/mv.png >> Pack.hh
xxd -i Resources/Countries/mw.png >> Pack.hh
xxd -i Resources/Countries/mx.png >> Pack.hh
xxd -i Resources/Countries/my.png >> Pack.hh
xxd -i Resources/Countries/mz.png >> Pack.hh
xxd -i Resources/Countries/na.png >> Pack.hh
xxd -i Resources/Countries/ne.png >> Pack.hh
xxd -i Resources/Countries/nf.png >> Pack.hh
xxd -i Resources/Countries/ng.png >> Pack.hh
xxd -i Resources/Countries/ni.png >> Pack.hh
xxd -i Resources/Countries/nl.png >> Pack.hh
xxd -i Resources/Countries/nm.png >> Pack.hh
xxd -i Resources/Countries/no.png >> Pack.hh
xxd -i Resources/Countries/np.png >> Pack.hh
xxd -i Resources/Countries/nr.png >> Pack.hh
xxd -i Resources/Countries/nu.png >> Pack.hh
xxd -i Resources/Countries/nz.png >> Pack.hh
xxd -i Resources/Countries/om.png >> Pack.hh
xxd -i Resources/Countries/pa.png >> Pack.hh
xxd -i Resources/Countries/pf.png >> Pack.hh
xxd -i Resources/Countries/pg.png >> Pack.hh
xxd -i Resources/Countries/ph.png >> Pack.hh
xxd -i Resources/Countries/pk.png >> Pack.hh
xxd -i Resources/Countries/pl.png >> Pack.hh
xxd -i Resources/Countries/pm.png >> Pack.hh
xxd -i Resources/Countries/pn.png >> Pack.hh
xxd -i Resources/Countries/pr.png >> Pack.hh
xxd -i Resources/Countries/pt.png >> Pack.hh
xxd -i Resources/Countries/pw.png >> Pack.hh
xxd -i Resources/Countries/py.png >> Pack.hh
xxd -i Resources/Countries/qa.png >> Pack.hh
xxd -i Resources/Countries/ro.png >> Pack.hh
xxd -i Resources/Countries/rs.png >> Pack.hh
xxd -i Resources/Countries/ru.png >> Pack.hh
xxd -i Resources/Countries/rw.png >> Pack.hh
xxd -i Resources/Countries/sa.png >> Pack.hh
xxd -i Resources/Countries/sb.png >> Pack.hh
xxd -i Resources/Countries/sc.png >> Pack.hh
xxd -i Resources/Countries/sd.png >> Pack.hh
xxd -i Resources/Countries/se.png >> Pack.hh
xxd -i Resources/Countries/sg.png >> Pack.hh
xxd -i Resources/Countries/sh.png >> Pack.hh
xxd -i Resources/Countries/si.png >> Pack.hh
xxd -i Resources/Countries/sk.png >> Pack.hh
xxd -i Resources/Countries/sl.png >> Pack.hh
xxd -i Resources/Countries/sm.png >> Pack.hh
xxd -i Resources/Countries/sn.png >> Pack.hh
xxd -i Resources/Countries/so.png >> Pack.hh
xxd -i Resources/Countries/sr.png >> Pack.hh
xxd -i Resources/Countries/st.png >> Pack.hh
xxd -i Resources/Countries/sv.png >> Pack.hh
xxd -i Resources/Countries/sy.png >> Pack.hh
xxd -i Resources/Countries/sz.png >> Pack.hh
xxd -i Resources/Countries/tc.png >> Pack.hh
xxd -i Resources/Countries/td.png >> Pack.hh
xxd -i Resources/Countries/tg.png >> Pack.hh
xxd -i Resources/Countries/th.png >> Pack.hh
xxd -i Resources/Countries/tj.png >> Pack.hh
xxd -i Resources/Countries/tl.png >> Pack.hh
xxd -i Resources/Countries/tm.png >> Pack.hh
xxd -i Resources/Countries/tn.png >> Pack.hh
xxd -i Resources/Countries/to.png >> Pack.hh
xxd -i Resources/Countries/tr.png >> Pack.hh
xxd -i Resources/Countries/tt.png >> Pack.hh
xxd -i Resources/Countries/tv.png >> Pack.hh
xxd -i Resources/Countries/tw.png >> Pack.hh
xxd -i Resources/Countries/tz.png >> Pack.hh
xxd -i Resources/Countries/ua.png >> Pack.hh
xxd -i Resources/Countries/ug.png >> Pack.hh
xxd -i Resources/Countries/uk.png >> Pack.hh
xxd -i Resources/Countries/us.png >> Pack.hh
xxd -i Resources/Countries/uy.png >> Pack.hh
xxd -i Resources/Countries/uz.png >> Pack.hh
xxd -i Resources/Countries/vc.png >> Pack.hh
xxd -i Resources/Countries/ve.png >> Pack.hh
xxd -i Resources/Countries/vg.png >> Pack.hh
xxd -i Resources/Countries/vh.png >> Pack.hh
xxd -i Resources/Countries/vi.png >> Pack.hh
xxd -i Resources/Countries/vn.png >> Pack.hh
xxd -i Resources/Countries/vu.png >> Pack.hh
xxd -i Resources/Countries/wf.png >> Pack.hh
xxd -i Resources/Countries/ws.png >> Pack.hh
xxd -i Resources/Countries/ye.png >> Pack.hh
xxd -i Resources/Countries/yt.png >> Pack.hh
xxd -i Resources/Countries/yu.png >> Pack.hh
xxd -i Resources/Countries/za.png >> Pack.hh
xxd -i Resources/Countries/zm.png >> Pack.hh
xxd -i Resources/Countries/zw.png >> Pack.hh
